/** Legacy URLs → live routes (301). Keep in sync with sitemap exclusions. */
export const legacyRedirects = [
  { source: '/about-us', destination: '/about', permanent: true },
  { source: '/contact-us', destination: '/contact', permanent: true },
  { source: '/get-in-touch', destination: '/contact', permanent: true },
  { source: '/quote', destination: '/contact', permanent: true },
  { source: '/book', destination: '/contact', permanent: true },
  { source: '/free-consultation', destination: '/contact', permanent: true },
  { source: '/discovery-call', destination: '/contact', permanent: true },
  { source: '/schedule', destination: '/contact', permanent: true },
  { source: '/work', destination: '/portfolio', permanent: true },
  { source: '/our-work', destination: '/portfolio', permanent: true },
  { source: '/projects', destination: '/portfolio', permanent: true },
  { source: '/case-study/:path*', destination: '/case-studies/:path*', permanent: true },
  { source: '/case-study', destination: '/case-studies', permanent: true },
  { source: '/proof', destination: '/case-studies', permanent: true },
  { source: '/reviews', destination: '/testimonials', permanent: true },
  { source: '/blog', destination: '/insights', permanent: true },
  { source: '/articles', destination: '/insights', permanent: true },
  { source: '/blog/:path*', destination: '/insights/:path*', permanent: true },
  { source: '/articles/:path*', destination: '/insights/:path*', permanent: true },
  { source: '/home', destination: '/', permanent: true },
  { source: '/index', destination: '/', permanent: true },
  { source: '/homepage', destination: '/', permanent: true },
  { source: '/videography', destination: '/services/videography', permanent: true },
  { source: '/video', destination: '/video-production', permanent: true },
  { source: '/drone-videography', destination: '/drone', permanent: true },
  { source: '/aerial-photography', destination: '/drone', permanent: true },
  { source: '/drone-video', destination: '/drone', permanent: true },
  { source: '/content-creation', destination: '/locations/content-creation-scotland', permanent: true },
  { source: '/locations', destination: '/locations/content-creation-scotland', permanent: true },
  { source: '/west-lothian', destination: '/west-lothian-content-creation', permanent: true },
  { source: '/fife', destination: '/fife-content-creation', permanent: true },
  { source: '/edinburgh', destination: '/edinburgh-content-creation', permanent: true },
  { source: '/glasgow', destination: '/video-production-scotland', permanent: true },
  { source: '/social-media-management', destination: '/social-media', permanent: true },
  { source: '/social-media-management-edinburgh', destination: '/social-media-edinburgh', permanent: true },
  { source: '/fife-video-production', destination: '/video-production-fife', permanent: true },
  { source: '/website-design', destination: '/web-design', permanent: true },
  { source: '/websites', destination: '/services/website-design', permanent: true },
  { source: '/services/websites', destination: '/services/website-design', permanent: true },
  { source: '/services/video', destination: '/services/videography', permanent: true },
  { source: '/services/social', destination: '/services/social-media-content', permanent: true },
  { source: '/marketing', destination: '/services', permanent: true },
  { source: '/digital-marketing', destination: '/services', permanent: true },
  { source: '/training/ai', destination: '/ai-chatgpt-training', permanent: true },
  { source: '/chatgpt-training', destination: '/ai-chatgpt-training', permanent: true },
  { source: '/construction-social-media', destination: '/social-media-for-construction', permanent: true },
  { source: '/trades-web-design', destination: '/web-design-for-trades-scotland', permanent: true },
  { source: '/services.html', destination: '/services', permanent: true },
  { source: '/contact.html', destination: '/contact', permanent: true },
  { source: '/portfolio.html', destination: '/portfolio', permanent: true },
  { source: '/about.html', destination: '/about', permanent: true },
  { source: '/pricing.html', destination: '/pricing', permanent: true },
  { source: '/insights.html', destination: '/insights', permanent: true },
  { source: '/case-studies.html', destination: '/case-studies', permanent: true },
  { source: '/web-design.html', destination: '/web-design', permanent: true },
  { source: '/video-production.html', destination: '/video-production', permanent: true },
  { source: '/social-media.html', destination: '/social-media', permanent: true },
] as const;

/** Redirect sources only — exclude from sitemap */
export const REDIRECT_PATHS = new Set(
  legacyRedirects.map((r) => r.source.replace(/^\//, '').replace(/\/:path\*$/, ''))
);
